# experiment parameter
SAMPLE_RATE: 16000                                                            # 采样率
WIN_LEN: 512                                                                  # 窗长
FFT_SIZE: 256                                                                 # fft大小
WIN_OFFSET: 256                                                               # 窗移
LR: 0.001                                                                     # 学习率
MAX_EPOCH: 60                                                                 # 训练轮数
EPSILON: 0.0000001                                                            #
USE_CV: True                                                                  # [True,False]，是否使用验证集
EVAL_STEP: 80000                                                               # 多少个batch进行一次CV
#EVAL_STEP: 1                                                               # 多少个batch进行一次CV
LOG_STEP: 500                                                                 # 多少个batch输出一次信息

# server setting
CUDA_ID: '0'                                                                  # 指定GPU编号
BATCH_SIZE: 12                                                                # 批处理数
NUM_WORK: 16                                                                   # 线程数


# environment parameter
project_root_path: '/home/imu_speech1/zhaofei/Fusion_Net'                     # 项目根目录

SPEECH_PATH: '/data01/zhaofei/data/Fusion-Net/cut_train_speech/'
MIX_PATH: '/data01/zhaofei/data/Fusion-Net/cut_train_mix/'

TRAIN_SPEECH_LST: '/data01/zhaofei/data/Fusion-Net/npy/train_speech.npy'          # 训练集(speech)配置文件名
TRAIN_MIX_LST: '/data01/zhaofei/data/Fusion-Net/npy/train_mix.npy'                # 训练集(mix)配置文件名
CV_SPEECH_LST: '/data01/zhaofei/data/Fusion-Net/npy/val_speech.npy'               # 验证集(speech)配置文件名
CV_MIX_LST: '/data01/zhaofei/data/Fusion-Net/npy/val_mix.npy'                     # 验证集(mix)配置文件名

OUTPUT_DIR: '/data01/zhaofei/result/'                                         # 输出根目录
BEST_MODEL: 'best.ckpt'                                                       # 默认最好模型名称
MID_MODEL: 'val.ckpt'                                                         # 默认中间模型名称
SAVE_BEST_ONLY: False                                                         # [True,False]:[仅保存最好的模型,保存中间模型]
WORKSPACE: '/Fusion_Net'                                                             # 子项目名称